<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LTA122IXLR" ignored="0" name="API Test" tests="4" failures="1" timestamp="21 Aug 2018 10:18:32 GMT" time="16.889" errors="0">
  <testcase name="verifyA006Response_0" time="12.25" classname="com.APBCBS.api.TestCases.VerifyA006Response"/>
  <testcase name="verifyA006Response_0" time="0.978" classname="com.APBCBS.api.TestCases.VerifyA006Response">
    <skipped/>
  </testcase> <!-- verifyA006Response_0 -->
  <testcase name="verifyA006Response_0" time="0.865" classname="com.APBCBS.api.TestCases.VerifyA006Response">
    <skipped/>
  </testcase> <!-- verifyA006Response_0 -->
  <testcase name="verifyA006Response_0" time="0.753" classname="com.APBCBS.api.TestCases.VerifyA006Response">
    <failure type="java.lang.AssertionError" message="expected [0] but found [8102]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [8102]
	at com.APBCBS.api.ApiClasses.A006API.postRequestWithValidData(A006API.java:36)
	at com.APBCBS.api.TestCases.VerifyA006Response.verifyA006Response_0(VerifyA006Response.java:22)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- verifyA006Response_0 -->
</testsuite> <!-- API Test -->
